### ISSUE TITLE
cant select tos directory

### ISSUE THREAD

**Issue by zubatto** [iwiwao/Tree-of-Savior-Addon-Manager#2]
how do i pick select tos directory? also which folder do i pick?
tried a couple of times to select on steamapps/common/TreeOfSavior but when i click find existing addons or try to install a new addon, a pop up still says please set a valid tos directory

**Comment by iwiwao** [comment]
That should be the correct directory - if the common/TreeOfSavior directory contains an "addons" and "data" directory, it will be considered valid.  

The initial selection only checks for the existence of those two directories, but does not test for valid permissions, which is done when you attempt to Update, etc.  

You may need to launch the addon manager as an administrator if your local user account does not have permissions to write to the "addons" and "data" directory.

*edit* - I forgot I added the permissions check to the directory selection.  But please spawn the manager as admin and let me know if you still receive the same error.
